formatter: "markdown table"

header-from: "docs/HEADER.md"

content: |-
  {{ .Header }}

  ## Usage

  ```hcl
  {{ include "examples/simple/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  mode: inject
